In [25]:
#Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [26]:
#Create a vector with values ranging from 10 to 49.
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
#Create a 3x3 matrix with values ranging from 0 to 8
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
a=np.array([1,2,0,0,4,0])
for i in range(len(a)):
    if a[i]==0:
        continue
    print(i)

0
1
4


In [29]:
# Create a 10x10 array with random values and find the minimum and maximum values.
import random
a=np.random.rand(10,10)
print(a)
print("\nMinimum value is: ",a.min())
print("Maximum value is: ",a.max())

[[0.14589619 0.57610621 0.95882163 0.71008523 0.56325053 0.49689081
  0.56756594 0.8450752  0.00471232 0.14013918]
 [0.60662433 0.27588243 0.44414524 0.4340943  0.36703935 0.37981113
  0.89516764 0.37856254 0.08183067 0.21342945]
 [0.65101285 0.68994016 0.41236622 0.27413973 0.20676117 0.70975705
  0.80486344 0.02897784 0.49187796 0.12989239]
 [0.07015024 0.28472365 0.92814828 0.99761459 0.00566525 0.88047725
  0.62356988 0.34031792 0.69541669 0.57202894]
 [0.75550741 0.25790608 0.83934032 0.72952066 0.59992898 0.9337775
  0.56857809 0.70438399 0.50035845 0.23074343]
 [0.72031667 0.91905628 0.24393728 0.7776519  0.57932463 0.01170804
  0.6491006  0.40632467 0.11988502 0.5974412 ]
 [0.47271691 0.7373267  0.11027128 0.7349699  0.58771667 0.80389796
  0.92801351 0.10175493 0.68310102 0.67750793]
 [0.47187122 0.4519724  0.36222735 0.92497635 0.11159749 0.71707287
  0.98732141 0.44891445 0.64840101 0.77884273]
 [0.39984721 0.52291452 0.84578221 0.02124813 0.83065158 0.16215049
  0.63782687 

In [30]:
#Create a random vector of size 30 and find the mean value
import numpy as np
import random
a=np.random.rand(30)
print(a)
print("\nMean of the vector is: ",a.mean())

[0.26830157 0.55403581 0.61480816 0.36859177 0.87084481 0.57438282
 0.71330669 0.43971772 0.85273878 0.90339073 0.10423774 0.86976645
 0.09604134 0.44309104 0.569308   0.61758045 0.66767726 0.03924983
 0.56024612 0.2100368  0.99789311 0.95681834 0.5723293  0.22809612
 0.23851734 0.0312681  0.86172014 0.40403101 0.28101852 0.25308669]

Mean of the vector is:  0.5054044189594147
